server:
  port: 8080

spring:
  redis:
    port: 6379
    host: 192.168.226.3
    password: 123456
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存数据的过期时间
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    # 配置mybatisplus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #xml文件的位置(resources下的mapper文件夹)
  mapper-locations: classpath:mapper/*.xml

reggie:
  path: D:\idea\reggie-project\src\main\resources\front\dish-images\

